
-define(UTP_DEFAULT_RTO,3000). %ms
-define(UTP_DEFAULT_RTT,800). %ms

-define(UTP_MAX_WND_INCREASE_BYTES_PER_RTT,3000). %bytes
-define(UTP_MAX_WINDOW_DECAY,100). %ms
-define(UTP_CCONTROL_TARGET,100).  %ms
-define(UTP_MIN_WINDOW_SIZE,100). %bytes

-define(UTP_DEFAULT_PACKET_SIZE,1435).
-define(UTP_DEFAULT_DISCOVER_TIME,30 * 60 * 1000).
-define(UTP_DEFAULT_MTU,576).

-define(UTP_RECV_BUFFER_MAX_SLOT,1024).
-define(UTP_SEND_BUFFER_MAX_SLOT,1024).

%NAT 29 seconds
-define(UTP_KEEPALIVE_INTERVAL,29000).


-define(UTP_SEQ_NR_MASK,16#FFFF).
-define(UTP_ACK_NR_MASK,16#FFFF).
-define(UTP_TIMESTAMP_MASK,16#FFFFFFFF).

-define(ETHERNET_MTU,1500).
-define(IPV4_HEADER_SIZE,20).
-define(IPV6_HEADER_SIZE,40).
-define(UDP_HEADER_SIZE,8).
-define(GRE_HEADER_SIZE,24).
-define(PPPOE_HEADER_SIZE,8).
-define(MPPE_HEADER_SIZE,2).
-define(FUDGE_HEADER_SIZE,36).
-define(TEREDO_MTU,1280).

-define(UDP_IPV4_MTU,(?ETHERNET_MTU - ?IPV4_HEADER_SIZE - ?UDP_HEADER_SIZE 
	- ?GRE_HEADER_SIZE - ?PPPOE_HEADER_SIZE - ?MPPE_HEADER_SIZE 
	- ?FUDGE_HEADER_SIZE)).
